# Generated by Django 4.2.30 on 2026-09-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_sede_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(blank=True)),
                ('enfermedad_actual', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('firmada', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='miapp.cita')),
            ],
        ),
        migrations.AddField(
            model_name='medicina',
            name='presentacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('dispensada', 'Dispensada'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='recetas/')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='miapp.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno_minutos', models.IntegerField(default=30)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='miapp.medico')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='miapp.sede')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('via_administracion', models.CharField(choices=[('oral', 'Oral'), ('topica', 'Tópica'), ('endovenosa', 'Endovenosa')], default='oral', max_length=20)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_tratamiento', models.CharField(max_length=100)),
                ('cantidad_total', models.CharField(max_length=50)),
                ('indicaciones', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_receta', to='miapp.medicina')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp.receta')),
            ],
        ),
    ]
