# Generated by Django 4.2.30 on 2026-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_consulta_medicina_presentacion_receta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='proveedor_videollamada',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='url_medico',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='url_paciente',
            field=models.URLField(blank=True),
        ),
    ]
