# Generated by Django 4.2.30 on 2026-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_cita_proveedor_videollamada_cita_sala_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Separadas por coma, ej: penicilina, ibuprofeno'),
        ),
    ]
